.PHONY: data/tabela_comparativa.csv clean main.pdf

GRAFICOS_COMPARATIVOS := $(addprefix autogenerated/graficos_comparativos/,foo.png)

all: main.pdf

main.pdf: autogenerated/tikzplots/aero_coef.tex
	latexmk

data/tabela_comparativa.csv: 
	curl -o "data/tabela_comparativa.csv"  "https://docs.google.com/spreadsheets/d/e/2PACX-1vQ7nkYMxBALTu0WOJhUMF4ooM3jaFrvR3rVfXsxmclZ1-P7w-E-ugnn2yVLbu0dy86XZrLqFLcnmpqB/pub?gid=0&single=true&output=csv"

GRAFICOS_COMPARATIVOS: src/python/graficos_comparativos.py data/tabela_comparativa.csv
	python3 src/python/graficos_comparativos.py

autogenerated/tikzplots/aero_coef.tex: data/perfis/* src/aero_coef.gnuplot
	gnuplot src/aero_coef.gnuplot

clean:
	latexmk -C
	rm -f data/tabela_comparativa.csv
	rm -rf autogenerated/*
